<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('ZF2 '. $this->translate('Skeleton Application'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/assets/css/main-min.css')
                        ->prependStylesheet($this->basePath() . '/assets/css/bui-min.css')
                        ->prependStylesheet($this->basePath() . '/assets/css/dpl-min.css') ?>
<style>
.container{margin-left:0;margin-top:0;width:auto;padding:20px 20px 0 20px;}.detail-page,.form-page,.search-page{padding:0;}
</style>
    </head>
    <body>
      <script type="text/javascript" src="<?php echo $this->basePath();?>/assets/js/jquery-1.8.1.min.js"></script>
  <script type="text/javascript" src="<?php echo $this->basePath();?>/assets/js/bui.js"></script>
  <script type="text/javascript" src="<?php echo $this->basePath();?>/assets/js/config.js"></script>
        <div class="container">
            <?php echo $this->content; ?>
        </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>
    </body>
</html>
