<div id="content" class="hide">
      <form id="J_Form" class="form-horizontal" action="<?php echo $this->url('admin' , array('controller' => 'role' , 'action' => 'save'));?>">
        <div class="row">
          <div class="control-group span8">
            <label class="control-label"><s>*</s>角色名称</label>
            <div class="controls">
              <input name="Name" type="text" data-rules="{required:true}" class="input-normal control-text">
            </div>
          </div>
        </div>
        <div class="row">
          <div class="control-group span8">
            <label class="control-label"><s>*</s>角色名称</label>
            <div class="controls">
              <input name="Name" type="text" data-rules="{required:true}" class="input-normal control-text">
            </div>
          </div>
        </div>
      </form>
</div>
<div id="grid" style="width:100%;"></div>
<script>
var gridW = $("#grid").width();
var data = [];
<?php foreach ($this->list as $role):?>
<?php 
$ResourceName = '';
        foreach ($role['resource'] as $k=>$v) {
        	$ResourceName .= $v['ResourceName'].',';
        }
        $role['resource'] = $ResourceName;
        ;?>
data.push(<?php echo json_encode($role)?>);
<?php endforeach;?>
BUI.use(['bui/grid','bui/data'],function (Grid,Data) {

    var columns = [{title : '角色',dataIndex :'Name'},
            {title : '角色别名',dataIndex :'CnName'},
            {title : '已绑定资源',dataIndex :'resource'},
            {title : '添加时间',dataIndex :'AddTime'},
            {title : '操作',renderer : function(){
              return '<span class="grid-command btn-edit">编辑</span>';
            }}
          ],
      //默认的数据
//       data = [
//         {id:'1',school:'武汉第一初级中学',enter:'1999-09-01',type: 'zou',outter:'2002-07-01',memo:'表现优异，多次评为三好学生'},
//         {id:'2',school:'武汉第一高级中学',enter:'2002-09-01',type: 'zou',outter:'2005-07-01',memo:'表现优异，多次评为三好学生'}
//       ],
      store = new Data.Store({
        data:data
      }),
      editing = new Grid.Plugins.DialogEditing({
        contentId : 'content',
        triggerCls : 'btn-edit'
      }),
      grid = new Grid.Grid({
        render : '#grid',
        columns : columns,
        width : gridW,
        forceFit : true,
        store : store,
        plugins : [Grid.Plugins.CheckSelection,editing],
        tbar:{
          items : [{
            btnCls : 'button button-small',
            text : '<i class="icon-plus"></i>添加角色',
            listeners : {
              'click' : addFunction
            }
          },
          {
            btnCls : 'button button-small',
            text : '<i class="icon-remove"></i>删除',
            listeners : {
              'click' : delFunction
            }
          }]
        }

      });
    grid.render();

    function addFunction(){
    	var newData = {isNew : true}
      editing.add(newData); //添加记录后，直接编辑
    }

    function delFunction(){
      var selections = grid.getSelection();
      store.remove(selections);
    }
    var logEl = $('#log');
    $('#btnSave').on('click',function(){

      var records = store.getResult();
      logEl.text(BUI.JSON.stringify(records));
    });
  });
</script>