<div id="content" class="hide">
      <form id="J_Form" class="form-horizontal" method="post" action="<?php echo $this->url('admin' , array('controller' => 'role' , 'action' => 'save'));?>">
      	<input name="id" type="hidden" value="" />
        <div class="row">
          <div class="control-group span8">
            <label class="control-label"><s>*</s>角色名称</label>
            <div class="controls">
              <input name="name" type="text" data-rules="{required:true}" class="input-normal control-text">
            </div>
          </div>
        </div>
        <div class="row">
          <div class="control-group span8">
            <label class="control-label"><s>*</s>角色别名</label>
            <div class="controls">
              <input name="cn_name" type="text" data-rules="{required:true}" class="input-normal control-text">
            </div>
          </div>
        </div>
      </form>
</div>
<div id="bind-content" class="hide">
<select name="opt"><option value="add">添加资源</option><option value="del">删除资源</option></select>
<span id="xx"></span>
</div>
<div id="grid" style="width:100%;"></div>
<script>
var gridW = $("#grid").width();
var data = [];
<?php foreach ($this->list as $role):?>
<?php 
$ResourceName = '';
        foreach ($role['resource'] as $k=>$v) {
        	$ResourceName .= $v['resource_name'].',';
        }
        $role['resource'] = $ResourceName;
        ;?>
data.push(<?php echo json_encode($role)?>);
<?php endforeach;?>
BUI.use(['bui/grid','bui/data','bui/form'],function (Grid,Data, Form) {

    var columns = [{title : '角色',dataIndex :'name'},
            {title : '角色别名',dataIndex :'cn_name'},
            {title : '已绑定资源',dataIndex :'resource'},
            {title : '添加时间',dataIndex :'add_time'},
            {title : '操作',renderer : function(){
              return '<span class="grid-command btn-edit">编辑</span><span class="grid-command btn-bind">绑定资源</span><span class="grid-command btn-del">删除</span>';
            }}
          ],
      store = new Data.Store({
        data:data
      }),
      editing = new Grid.Plugins.DialogEditing({
        contentId : 'content',
        triggerCls : 'btn-edit',
        editor:{
			success: function() {
				var edtor = this,form = edtor.get('form'),
                editType = editing.get('editType');
				form.valid();
                if (form.isValid()) {
                	form.ajaxSubmit({ //表单异步提交
                        url: '<?php echo $this->url('admin/default' , array('controller' => 'role' , 'action' => 'save'));?>',
                        method: 'post',
                        success: function (data) {

                            if (data.code != 0) {
                                BUI.Message.Alert(data.msg, 'error');
                            } else {
                                if (editType == 'add') {
//                                     store.add(data.Data);
                                } else {
                                    record = form.serializeToObject();
                                    editing.saveRecord(record);
                                }
                            	edtor.accept();
                            }

                        },
                        error: function () {
                            BUI.Message.Alert(data.msg, 'error');
                        }
                    });
                }
			}
        }
      }),bediting = new Grid.Plugins.DialogEditing({
          contentId : 'bind-content',
          triggerCls : 'btn-bind',
          editor: {
				content:function() {

		        	var type = 'add';
		    		var role = '1';
		    		$.ajax({
		    			type:'POST',
		    			url:'/ajax/getResource',
		    			data:{type : type, role : role},
		    			dataType:'json',
		    			cache:false,
		    			success:function(s) {
		    				if (s.code == 0) {
		    					var html = '<table class="table">';
		    					html += '<tr>';
		    					html += '<th width=60>全选<input type="checkbox" name="sAll" value="0" /> </th><th>资源</th><th>控制器</th><th>动作</th>';
		    					html += '</tr>';
		    					s = s.data;
		    					for (var i in s) {
		    						html += '<tr>';
		    						html += '<td><input type="checkbox" name="resourceItem" value="'+s[i].Name+'" />'+i+'</td>';
		    						html += '<td>'+s[i].Name+'</td>';
		    						html += '<td>'+s[i].ControllerName+'</td>';
		    						html += '<td>'+s[i].ActionName+'</td>';
		    						html += '</tr>';
		    					}
		    					html += '</table>';
		    					$("#xx").html(html);
		    					$("input[name='sAll']").bind('click', function(){
		    						if ($(this).is(':checked')) {
		    							$("input[name='resourceItem']", $("#resourceLists")).prop('checked', this.checked);
		    						} else {
		    							$("input[name='resourceItem']", $("#resourceLists")).removeAttr('checked');
		    						}
		    					})
		    				} else {
		    					alert(s.msg);
		    				}
		    			}
		    		});
				}
          }
        }),
      grid = new Grid.Grid({
        render : '#grid',
        columns : columns,
        width : gridW,
        forceFit : true,
        store : store,
        plugins : [Grid.Plugins.CheckSelection,editing, bediting],
        tbar:{
          items : [{
            btnCls : 'button button-small',
            text : '<i class="icon-plus"></i>添加角色',
            handler:function(){addFunction();}
//             listeners : {
//               'click' : addFunction
//             }
          },
          {
            btnCls : 'button button-small',
            text : '<i class="icon-remove"></i>删除',
            listeners : {
              'click' : delFunction
            }
          }]
        }

      });
    grid.render();
    function addFunction(){
    	var myDate = new Date();
        var add_time = '<?php echo date('Y-m-d H:i:s');?>';
    	var newData = {isNew : true, add_time: add_time};
      editing.add(newData); //添加记录后，直接编辑
    }

    function delFunction(){
      var selections = grid.getSelection();
      if (selections.length) {
          var params = [];
          for (var i in selections) {
			params.push(selections[i].id);
          }
		$.post('<?php echo $this->url('admin/default' , array('controller' => 'role' , 'action' => 'delete'));?>', {id:params}, function(s) {
			if (s.code == 0) {
				store.remove(selections);
			}
		});
      }
    }
    var logEl = $('#log');
    $('#btnSave').on('click',function(){

      var records = store.getResult();
      logEl.text(BUI.JSON.stringify(records));
    });
    grid.on('cellclick',function(ev){
        var sender = $(ev.domTarget); //点击的Dom
        var record = ev.record;
        if(sender.hasClass('btn-del')){
          BUI.Message.Confirm('确认要删除选中的记录么？',function(){
        	  $.post('<?php echo $this->url('admin/default' , array('controller' => 'role' , 'action' => 'delete'));?>', {id:record.id}, function(s) {
        			if (s.code == 0) {
        				store.remove(record);
        			}
        		});
         },'question');
        }
      });
  });
</script>